# Generated by Django 2.0.1 on 2018-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_num',
            field=models.IntegerField(default=0),
        ),
    ]
